### ISSUE TITLE
Add message input box

### ISSUE THREAD

**Issue by ninest** [ninest/direct-contact#1]
Using `?text=` from [universal links](https://faq.whatsapp.com/iphone/how-to-link-to-whatsapp-from-a-different-app/?lang=en), add a text box that allows the user to type out a message to pre-fill the WhatsApp chat. This will be useful in sending template messages to multiple people

**Comment by bonniesimon** [comment]
I would love to take this. I did contact you on reddit a few months back. My exams were going on then and after that I forgot.
Could you make this repo Hacktoberfest viable so that my contributions will count to hacktoberfest too!

Do let me know.

**Comment by ninest** [comment]
Done! Added the "hacktoberfest" tag
